name: rudr_surveyor
description: RUDR SURVEYOR - Land Measurement and Surveyor utility app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/rudr_logo.png
